

const marketingData = {
    promotions:
    {
        id: 1,
        title: "Special Offer",
        description: "Get 20% off on all products. Limited time offer!",
        expires: "2024-06-30",
        btn: "Click Here",
        image: "https://raw.githubusercontent.com/itskingsclub/kingsclub-marketing/main/assets/coin.png",
        link: "/special-offers",
    },
    banners: [
        {
            id: 1,
            title: "Start Play and Earn Money",
            description: "Get 20% off on all products. Limited time offer!",
            btn: "Play Games",
            image: "https://raw.githubusercontent.com/itskingsclub/kingsclub-marketing/main/assets/coin.png",
            link: "/special-offers",
        },
        {
            id: 2,
            title: "Special Offer",
            description: "Get 20% off on all products. Limited time offer!",
            btn: "Click Here",
            image: "https://raw.githubusercontent.com/itskingsclub/kingsclub-marketing/main/assets/coin.png",
            link: "/new-arrivals",
        },
    ],
    contactDetail: {
        "whatsapp": "9116724908",
        "telegram": "9116724908",
        "email": "help.kingsclub@gmail.com",
    },
    paymentDetail: {
        "account_number": "61325426753",
        "ifsc_code": "SBIN0032381",
        "bank_name": "State Bank of India",
        "acount_holder_name": "Mukesh Jat",
        "Paytm": "9116724908",
        "Phonepay": "9116724908",
        "qr_code": "https://raw.githubusercontent.com/itskingsclub/kingsclub-marketing/main/assets/qr.jpg",
    },
    cancelReasons: {
        beforeGame: [
            "I want to join another table",
            "No one can joining the table",
            "I have some urgent work",
            "I want to create another challenge",
            "I have network issue",
        ],
        afterGame: [
            "Opponent Didn't Came on Ludo King",
            "Ludo King application was not working",
            "Invalid Room Code",
            "Opponent use Diamond",
        ]
    },
    banks: [
        "State Bank of India (SBI)",
        "HDFC Bank",
        "ICICI Bank",
        "Punjab National Bank (PNB)",
        "Axis Bank",
        "Canara Bank",
        "Bank of Baroda (BoB)",
        "Union Bank of India",
        "Bank of India (BOI)",
        "IDBI Bank",
        "Indian Bank",
        "Central Bank of India",
        "IndusInd Bank",
        "Yes Bank",
        "Kotak Mahindra Bank",
        "Federal Bank",
        "Karur Vysya Bank",
        "South Indian Bank",
        "UCO Bank",
        "Andhra Bank",
        "Vijaya Bank",
        "Oriental Bank of Commerce (OBC)",
        "Syndicate Bank",
        "Dena Bank",
        "Corporation Bank",
        "Indian Overseas Bank (IOB)",
        "Punjab & Sind Bank",
        "RBL Bank",
        "Standard Chartered Bank",
        "DBS Bank India",
        "Citi Bank",
        "HSBC Bank",
        "Bank of Maharashtra",
        "Allahabad Bank",
        "State Bank of Hyderabad",
        "State Bank of Bikaner & Jaipur",
        "State Bank of Patiala",
        "State Bank of Travancore",
        "State Bank of Mysore",
        "State Bank of Sikkim",
        "State Bank of Indore",
        "State Bank of Raipur",
        "State Bank of Karnatak",
        "State Bank of Maharastra",
        "State Bank of Gujarat",
        "State Bank of Tamil Nadu",
        "State Bank of West Bengal",
        "State Bank of Jharkhand",
        "State Bank of Rajasthan",
        "State Bank of Orissa",
        "State Bank of Uttaranchal",
        "State Bank of Haryana",
        "State Bank of Bihar",
        "State Bank of Punjab",
        "State Bank of Delhi",
        "State Bank of Assam",
        "State Bank of Trivancore",
        "State Bank of Saurashtra",
        "State Bank of Bikaner",
        "State Bank of Patiala",
        "State Bank of Mysore",
        "State Bank of Indore",
        "State Bank of Raipur",
        "State Bank of Karnatak",
        "State Bank of Maharastra",
        "State Bank of Gujarat",
        "State Bank of Tamil Nadu",
        "State Bank of West Bengal",
        "State Bank of Jharkhand",
        "State Bank of Rajasthan",
        "State Bank of Orissa",
        "State Bank of Uttaranchal",
        "State Bank of Haryana",
        "State Bank of Bihar",
        "State Bank of Punjab",
        "State Bank of Delhi",
        "State Bank of Assam",
        "State Bank of Trivancore",
        "State Bank of Saurashtra",
        "State Bank of Bikaner",
        "State Bank of Patiala",
        "State Bank of Mysore",
        "State Bank of Indore",
        "State Bank of Raipur",
        "State Bank of Karnatak",
        "State Bank of Maharastra",
        "State Bank of Gujarat",
        "State Bank of Tamil Nadu",
        "State Bank of West Bengal",
        "State Bank of Jharkhand",
        "State Bank of Rajasthan",
        "State Bank of Orissa",
        "State Bank of Uttaranchal",
        "State Bank of Haryana",
        "State Bank of Bihar",
        "State Bank of Punjab",
        "State Bank of Delhi",
        "State Bank of Assam",
        "State Bank of Trivancore",
        "State Bank of Saurashtra",
        "State Bank of Bikaner"
    ],
};

module.exports = marketingData;